package com.personal.student_management.data.local.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.Date

/**
 * Represents a student entity in the database.
 *
 * @param id The unique identifier for the student (auto-generated by Room).
 * @param firstName The first name of the student.
 * @param lastName The last name of the student.
 * @param dateOfBirth The date of birth of the student.
 * @param photo The file path or URL of the student's photo.
 */
@Entity(tableName = "students")
data class StudentEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val firstName: String,
    val lastName: String,
    val dateOfBirth: Long,
    val photo: String
)

